### PR TITLE
[HB-6536] Updated adapter to use InMobi bidding API

### PR DESCRIPTION
**Pull request by bwised**
https://chartboost.atlassian.net/browse/HB-6536

Bid support with InMobi, SDK 10.6.7.

Their documentation:

[Bidding Integration with InMobi SDK.pdf](https://github.com/ChartBoost/chartboost-mediation-android-adapter-inmobi/files/15298686/Bidding.Integration.with.InMobi.SDK.pdf)

### CODE REVIEW

**Review by bichenwang — APPROVED** [review]

**Comment by bwised** [comment]
I'm missing a key part here, from their documentation, pertaining to loading the ad with some additional data.

**Comment by bichenwang** [comment]
oh yeah. probably need to load from a bid. could scrounge around with the `.` on the ad objects to see if they take in an adm somewhere.

**Comment by bwised** [comment]
I addressed it.  I also attached their documentation to the description if anybody needs to look at it.

**Comment by bichenwang** [comment]
neat. double lgtm

**Comment by bwised** [comment]
I found a sneaky issue that I fixed in commit https://github.com/ChartBoost/chartboost-mediation-android-adapter-inmobi/pull/57/commits/4452f79d523571c580367ec4f7a7d7922c40c4a0.  I needed to change the code so that the bidding version of load is not used if the byte array length is 0, which was happening even for the non-programatic placements.

**Pull request merged**
